name: cpu-tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  cpu-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build CPU test image (vllm-test target)
        run: docker build --target vllm-test -t vllm-cpu-test -f docker/Dockerfile.cpu .

      - name: Run min_tokens tests (V1)
        run: docker run --rm -e VLLM_USE_V1=1 --entrypoint /bin/bash vllm-cpu-test -lc "pytest tests/v1/test_min_tokens.py -v -s -rA --maxfail=1"

