name: cpu-tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  cpu-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build CPU test image
        run: docker build -t vllm-cpu-test -f docker/Dockerfile.cpu .

      - name: Run min_tokens tests (V1)
        run: docker run --rm -e VLLM_USE_V1=1 vllm-cpu-test /bin/bash -lc "pytest tests/v1/test_min_tokens.py -v --maxfail=1"

