name: Min Tokens (V1) CPU Tests

on:
  workflow_dispatch: {}
  push:
    branches:
      - fix/test-min-tokens
    paths:
      - 'tests/v1/test_min_tokens.py'
      - 'vllm/**'
      - 'docker/Dockerfile.cpu.legacy'
      - '.github/workflows/min-tokens.yml'
  pull_request:
    paths:
      - 'tests/v1/test_min_tokens.py'
      - 'vllm/**'
      - 'docker/Dockerfile.cpu.legacy'
      - '.github/workflows/min-tokens.yml'

jobs:
  cpu-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Docker version
        run: |
          docker version

      - name: Build legacy CPU test image
        run: |
          docker build -f docker/Dockerfile.cpu.legacy --target vllm-test -t vllm-cpu-test . | cat

      - name: Run V1 min_tokens tests
        run: |
          docker run --rm -e VLLM_USE_V1=1 vllm-cpu-test bash -lc "pytest tests/v1/test_min_tokens.py -v --maxfail=1"


