name: Tensor Swap Optimization Test & Benchmark (V1) CPU
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - optimize-tensor-swap-performance
jobs:
  cpu-benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show Docker version
        run: |
          docker version
      - name: Build optimized CPU test image
        id: build_optimized
        run: |
          IMAGE_ID=$(docker build -f docker/Dockerfile.cpu.legacy --target vllm-test -t vllm-cpu-test-optimized . -q)
          echo "image=${IMAGE_ID}" >> "$GITHUB_OUTPUT"
      - name: Build baseline CPU test image (full-row copy)
        id: build_baseline
        run: |
          IMAGE_ID=$(docker build -f docker/Dockerfile.cpu.legacy --build-arg VLLM_BASELINE_SWAP=1 --target vllm-test -t vllm-cpu-test-baseline . -q)
          echo "image=${IMAGE_ID}" >> "$GITHUB_OUTPUT"
      - name: Show built images
        run: |
          docker images | grep vllm-cpu-test || true
      - name: Run correctness tests (optimized)
        run: |
          docker run --rm -e VLLM_USE_V1=1 ${{ steps.build_optimized.outputs.image }} bash -lc "pytest tests/v1/worker/test_gpu_input_batch.py::test_swap_states_in_input_batch -v --tb=short"
      - name: Run tensor swap benchmark (optimized, 8K)
        run: |
          docker run --rm -e VLLM_USE_V1=1 ${{ steps.build_optimized.outputs.image }} bash -lc "python benchmarks/overheads/benchmark_tensor_swap.py --max-model-len 8192 --num-trials 30 --mode optimized"
      - name: Run tensor swap benchmark (optimized, 32K) 
        run: |
          docker run --rm -e VLLM_USE_V1=1 ${{ steps.build_optimized.outputs.image }} bash -lc "python benchmarks/overheads/benchmark_tensor_swap.py --max-model-len 32768 --num-trials 20 --mode optimized"
      - name: Run tensor swap benchmark (optimized, 65K)
        run: |
          docker run --rm -e VLLM_USE_V1=1 ${{ steps.build_optimized.outputs.image }} bash -lc "python benchmarks/overheads/benchmark_tensor_swap.py --max-model-len 65536 --num-trials 15 --mode optimized"
      - name: Run tensor swap benchmark (baseline, 8K)
        run: |
          docker run --rm -e VLLM_USE_V1=1 ${{ steps.build_baseline.outputs.image }} bash -lc "python benchmarks/overheads/benchmark_tensor_swap.py --max-model-len 8192 --num-trials 30 --mode baseline"
      - name: Run tensor swap benchmark (baseline, 32K)
        run: |
          docker run --rm -e VLLM_USE_V1=1 ${{ steps.build_baseline.outputs.image }} bash -lc "python benchmarks/overheads/benchmark_tensor_swap.py --max-model-len 32768 --num-trials 20 --mode baseline"
      - name: Run tensor swap benchmark (baseline, 65K)
        run: |
          docker run --rm -e VLLM_USE_V1=1 ${{ steps.build_baseline.outputs.image }} bash -lc "python benchmarks/overheads/benchmark_tensor_swap.py --max-model-len 65536 --num-trials 15 --mode baseline"