name: Tensor Swap Benchmark (V1) CPU
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'benchmarks/overheads/benchmark_tensor_swap.py'
      - 'vllm/v1/worker/gpu_input_batch.py'
      - 'docker/Dockerfile.cpu.legacy'
      - '.github/workflows/tensor-swap-benchmark.yml'
  push:
    paths:
      - 'benchmarks/overheads/benchmark_tensor_swap.py'
      - 'vllm/v1/worker/gpu_input_batch.py'
jobs:
  cpu-benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show Docker version
        run: |
          docker version
      - name: Build legacy CPU test image
        run: |
          docker build -f docker/Dockerfile.cpu.legacy --target vllm-test -t vllm-cpu-test . | cat
      - name: Run tensor swap benchmark
        run: |
          docker run --rm -e VLLM_USE_V1=1 vllm-cpu-test bash -lc "python benchmarks/overheads/benchmark_tensor_swap.py --max-model-len 8192 --num-trials 50"
      - name: Run tensor swap benchmark (large context)
        run: |
          docker run --rm -e VLLM_USE_V1=1 vllm-cpu-test bash -lc "python benchmarks/overheads/benchmark_tensor_swap.py --max-model-len 32768 --num-trials 25"